[package]
name = "gemini-like-poster"
version = "0.1.0"
authors = ["Kaito Takanami"]
license = "MIT"
entrypoint = "main.typ"
description = "Gemini-like Poster Template for Typst."
repository = "https://github.com/taka255/gemini-like-poster"
keywords = ["poster", "template"]
exclude = ["history/*"]

[template]
path = "main.typ"
