[package]
name = "gemini-like-poster"
version = "0.1.0"
entry = "main.typ"
authors = ["Kaito Takanami"]
license = "MIT"
description = "Gemini-like Poster Template for Typst."
repository = "https://github.com/taka255/gemini-like-poster"
keywords = ["poster", "template"]

[template]
path = "main.typ"
